module:
    hugoVersion:
        extended: true
        min: "0.87.0"

menu:
    main: []
    social:
        - identifier: github
          name: GitHub
          url: "https://github.com/benzerer"
          params:
              icon: brand-github
        - identifier: linkedin
          name: LinkedIn
          url: "https://www.linkedin.com/in/nopdanai-dejvorakul/"
          params:
              icon: brand-linkedin
        - identifier: facebook
          name: Facebook
          url: "https://www.facebook.com/bn.intm"
          params:
              icon: brand-facebook

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        compact: false
        emoji: 💻
        subtitle: Data enthusiast x Software engineer
        avatar:
            enabled: true
            local: false
            src: https://media.licdn.com/dms/image/D4E03AQE4TQZOW0adGA/profile-displayphoto-shrink_800_800/0/1685604339102?e=1692835200&v=beta&t=BQIxpIDgCsyVDqDjydvEctC3uMxPc6EdMeKHCwnZnbM

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

markup:
    goldmark:
        renderer:
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4

permalinks:
    post: "/p/:slug/"
    page: "/:slug/"

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100
        - name: categories
          weight: 200
